### ISSUE TITLE
How do I add `#` in front of the colour values in the image outputs?

### ISSUE THREAD

**Issue by Vibhav201** [Aonodensetsu/prev_gen#3]
Hey, thanks for making that amazing CLI tool for prev_gen.

I want to add `#` in front of colour values in the SVG output for easy copying and pasting. Can this be done using the CLI tool?

Also, my suggestion is you should include the `#` in the HEX values by default.

**Comment by Aonodensetsu** [comment]
i initially had the # but eventually decided to drop it, since 99% of tools working with hex support that form and it was actually me having issues with copying that led to it :p
If you just want the list of colors, then converting to YAML will be easiest for that. Adding hashes then is a simple find-replace.
cli tool:
```bash
prev-gen image.svg --out yml
```
python:
```python
from prev_gen import Reverse, YAML
YAML(Reverse('image.svg')).write('image.yml')
```

**Comment by Vibhav201** [comment]
No, actually I don't want to recreate the list of colours. 

I was asking if the `#` sign can be added to the colour values in the preview images using the CLI tool? If not using the CLI tool, what is the way to achieve that?

Here is an example:
![image](https://github.com/Aonodensetsu/prev_gen/assets/86820586/e6e76fdc-cb6b-42d3-a6fa-dcc0372e04ab)

**Comment by Aonodensetsu** [comment]
You can open the svg file in a text editor, and for every line that has use="hex" can find-replace the hex.
Using sed: `s|\(use="hex"[^>]*>\)|\1#|`

**Comment by Vibhav201** [comment]
Thanks, but how can I run this exactly?

**Comment by Aonodensetsu** [comment]
Sed specifically is a commandline tool in linux but it uses regex, as do most other text editors, such as notepad++.
You can also use sed online: https://sed.js.org/

**Comment by Aonodensetsu** [comment]
I'll note your suggestion down for later

**Comment by Vibhav201** [comment]
Thanks a lot, that works like a charm.

> I'll note your suggestion down for later

I think including the `#` is better because while selecting the colour code from the SVG (to view SVGs I use my browser btw), I can double click to select the code without the `#` and triple click to select the code with the `#`. But, this is your project, so I respect your choice as well.  :)

**Comment by Aonodensetsu** [comment]
@Vibhav added the hash in 5.1.0 via a Settings toggle
